package view;

import dao.DriverDAO;
import dao.DriverTeamDAO;
import dao.RegisteredDAO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import model.Driver;
import model.DriverTeam;
import model.Registered;
import model.Team;
import model.Stage;

public class SelectDriverFrm extends javax.swing.JFrame implements ActionListener{
    ArrayList<Driver> listdriver = new ArrayList<>();
    DefaultListModel<String> model = new DefaultListModel<>();
    private Registered r = new Registered();
    private Stage s;
    private Team t;
    private Driver d = new Driver();
    private DriverTeam dt = new DriverTeam();

    public SelectDriverFrm(String selectedTeam, Stage s, Team t) {        
        this.s = s;
        this.t = t;
        initComponents();
        loadDataToList(selectedTeam);
        r.setStage(s);
        btnRegister.addActionListener(this);
        
    }
    
    public void loadDataToList(String teamName){
        DriverDAO dd = new DriverDAO();     
        listdriver = dd.getDriverList(teamName);       
        for(Driver a : listdriver){
            model.addElement(a.getName());
        }          
        lstdriver.setModel(model);
    }
    
    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource() == btnRegister){
            for(int i = 0; i < listdriver.size(); i++){
                if(listdriver.get(i).getName().equals(lstdriver.getSelectedValue()) ){
                    d.setId(listdriver.get(i).getId());
                }
            }
            dt.setDriver(d);
            dt.setTeam(t);
            DriverTeamDAO dtd = new DriverTeamDAO(); 
            dtd.getDriverTeamid(dt);
            r.setDriverteam(dt);
            RegisteredDAO rd = new RegisteredDAO();
            rd.registerDriver(r);
            JOptionPane.showMessageDialog(this, "Dang ki thanh cong");
            (new OrganizerHomeFrm()).setVisible(true);
            this.dispose();
        }
        
          
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstdriver = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(lstdriver);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Chọn 2 tay đua");

        btnRegister.setText("Đăng kí");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstdriver;
    // End of variables declaration//GEN-END:variables

    
}
